/***********************************
                    CREANDO TABLAS
************************************/

CREATE TABLE TBL_USUARIO(
CODUSU NUMERIC(10) NOT NULL  PRIMARY KEY,
NOMUSU VARCHAR(60) NOT NULL UNIQUE,
CLAVEUSU VARCHAR(45) NOT NULL,
ESTADOUSU CHAR(11) NOT NULL
);

CREATE TABLE TBL_ROL(
CODROL NUMERIC(10) NOT NULL PRIMARY KEY,
NOMROL VARCHAR(60) NOT NULL
);

CREATE TABLE TBL_OPERACION(
CODOPE NUMERIC(10) NOT NULL PRIMARY KEY,
NOMOPE VARCHAR(60) NOT NULL
)

CREATE TABLE TBL_MODULO(
CODMODU NUMERIC(10) NOT NULL PRIMARY KEY,
NOMMODU VARCHAR(60) NOT NULL
)

COMMIT;




/***********************************
                    CREAR SEQUENCIA
************************************/
CREATE SEQUENCE SEQ_USUARIO;
CREATE SEQUENCE SEQ_ROL;
CREATE SEQUENCE SEQ_OPERACION;
CREATE SEQUENCE SEQ_MODULO;










